# Generated by Django 4.2 on 2025-05-22 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('is_amo_member', models.BooleanField(default=False)),
                ('is_alo_member', models.BooleanField(default=False)),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.cohort')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('OFFERING', 'Offering'), ('TITHE', 'Tithe'), ('CONTRIBUTION', 'Contribution'), ('MISSION', 'Mission'), ('LUNCH', 'Lunch Money'), ('FUNDRAISING', 'Fundraising')], max_length=20)),
                ('mission_payment_type', models.CharField(blank=True, choices=[('20_BOB', '20 Bob Challenge'), ('50_BOB', '50 Bob Challenge'), ('COHORT', 'Cohort Payment'), ('FAMILY', 'Family Payment'), ('MINI_CONCERT', 'Mini Fundraiser Concert'), ('MEGA_FUNDRAISER', 'Mega Fundraiser')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.member')),
            ],
        ),
    ]
