# Generated by Django 4.2 on 2025-05-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_alo_member',
            new_name='is_alo',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='is_amo_member',
            new_name='is_amo',
        ),
    ]
